[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force=false

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"